import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  topListItem: {
    marginRight: 5,
    padding: 5,
    alignItems: 'center',
    width: 120,
    borderColor: '#000000',
    borderWidth: 1,
    borderRadius: 10,
    position: 'relative',
    height: 250,
  },
  topImage: {
    width: 100,
    height: 100,
  },
  topTitle: {
    fontSize: 12,
    marginTop: 5,
    color: '#000000',
  },
  topPrice: {
    fontSize: 15,
    fontWeight: 'bold',
    color: 'red',
    position: 'absolute',
    left: 10,
    bottom: 30,
  },
  bottomListItem: {
    margin: 10,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 10,
    paddingBottom: 10,
    position: 'relative',
    height: 150,
  },
  bottomImage: {
    width: 130,
    height: 130,
    left: 5,
    position: 'absolute',
    left: 15,
    bottom: 15,
  },
  bottomTitle: {
    fontSize: 16,
    color: '#000000',
    right: 15,
    left: 150,
    position: 'absolute',
  },
  bottomPrice: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'green',
    right: 15,
    bottom: 35,
    position: 'absolute',
  },
  addToCartButton: {
    // marginTop: 8,
    backgroundColor: '#1E90FF',
    padding: 2,
    borderRadius: 5,
    height: 20,
    width: 55,
    bottom: 5,
    left: 10,
    position: 'absolute',
  },
  addToCart: {
    // marginTop: 8,
    backgroundColor: '#1E90FF',
    padding: 2,
    borderRadius: 5,
    height: 20,
    width: 55,
    bottom: 10,
    right: 10,
    position: 'absolute',
  },
  addToCartButtonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 10,
  },
  bottomListTitleContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  viewMoreButtonText: {
    color: 'red',
    fontWeight: 'bold',
    fontSize: 15,
    marginTop: 10,
    right: 10,
    // position: 'absolute',
  },
});
